"""Human-first HTML layout for the daily US market report."""

from __future__ import annotations

from typing import Mapping


def render_good_market_html(
    *,
    context: Mapping[str, str],
    axis_rows: str,
    transmission_cards: str,
    sector_cards: str,
    theme_cards: str,
    phase_guide: str,
    checklist: str,
    news_cards: str,
    today_rows: str,
    upcoming_rows: str,
    market_rows: str,
    sector_rows: str,
    theme_rows: str,
    leader_rows: str,
    macro_rows: str,
) -> str:
    """Render conclusions first and move dense source tables behind details."""

    c = context
    return f"""<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>미국 시장 변화 리포트 · {c['as_of']}</title>
<style>
:root{{--paper:#f4f1ea;--ink:#17211d;--muted:#667069;--line:#d8d4ca;--panel:#fffdf8;--green:#1f6b4f;--green-soft:#e4eee8;--amber-soft:#f5ead4;--navy:#173448}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;color:var(--ink);font-family:Pretendard,"Noto Sans KR","Segoe UI",sans-serif;background:var(--paper);line-height:1.6}}a{{color:inherit}}.wrap{{width:min(1180px,calc(100% - 40px));margin:auto}}
header{{padding:42px 0 26px;background:var(--panel);border-bottom:1px solid var(--line)}}.eyebrow,.kicker{{color:var(--green);font-size:10px;font-weight:800;letter-spacing:.15em}}h1{{margin:7px 0 8px;font-family:Georgia,"Noto Serif KR",serif;font-size:clamp(34px,5vw,58px);line-height:1.08;letter-spacing:-.04em}}header p{{max-width:880px;margin:0;color:var(--muted);font-size:14px}}.meta{{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}}.meta b,.phase{{padding:5px 9px;border:1px solid var(--line);border-radius:999px;background:#fff;font-size:10px}}
nav{{position:sticky;top:0;z-index:10;background:#f4f1eaf2;border-bottom:1px solid var(--line);backdrop-filter:blur(10px)}}nav .wrap{{display:flex;gap:18px;overflow:auto}}nav a{{padding:11px 0;color:var(--muted);font-size:11px;font-weight:700;text-decoration:none;white-space:nowrap}}main{{padding:24px 0 70px}}
.brief{{display:grid;gap:12px}}.verdict,.quick-card,.section,.change-card,.transmission,.lead-card,.news-card{{border:1px solid var(--line);background:var(--panel);box-shadow:0 8px 25px #1734480b}}.verdict,.section{{border-radius:16px}}.verdict{{padding:26px}}.verdict h2{{max-width:970px;margin:8px 0 12px;font-size:25px;line-height:1.35;letter-spacing:-.03em}}.verdict p{{margin:0;color:var(--muted);font-size:13px}}.quick-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}.quick-card{{min-height:138px;padding:17px;border-radius:12px}}.quick-card>span{{display:block;color:var(--muted);font-size:9px;font-weight:750}}.quick-card strong{{display:block;margin:7px 0 8px;font-size:17px;line-height:1.35}}.quick-card p{{margin:0;color:var(--muted);font-size:10px}}.quick-card.market{{color:#fff;background:var(--navy);border-color:var(--navy)}}.quick-card.market>span,.quick-card.market p{{color:#b6cad4}}
.section{{margin-top:16px;overflow:hidden}}.section-head{{display:flex;justify-content:space-between;align-items:end;padding:20px 22px;border-bottom:1px solid var(--line)}}.section-head h2{{margin:4px 0 0;font-size:20px;letter-spacing:-.02em}}.section-head p{{max-width:570px;margin:0;color:var(--muted);font-size:11px;text-align:right}}.changes{{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:16px}}.change-card{{min-height:145px;padding:18px;border-radius:12px}}.change-card>span{{color:var(--muted);font-size:10px}}.change-card b{{display:block;margin:7px 0 8px;font-size:18px}}.change-card p{{margin:0;color:var(--muted);font-size:11px}}
.macro-grid{{display:grid;grid-template-columns:.9fr 1.1fr}}.axis-list{{border-right:1px solid var(--line)}}.axis-row{{padding:15px 18px;border-bottom:1px solid var(--line)}}.axis-row:last-child{{border-bottom:0}}.axis-row>div{{display:flex;justify-content:space-between}}.axis-row span{{color:var(--muted);font-size:11px}}.axis-row strong{{font-size:13px}}.axis-row.positive strong{{color:var(--green)}}.axis-row.caution strong{{color:#a4483d}}.axis-row p{{margin:5px 0;color:#36413c;font-size:11px}}.axis-row small{{color:var(--muted);font-size:10px}}.transmissions{{display:grid;gap:10px;padding:14px}}.transmission{{padding:15px;border-radius:11px;box-shadow:none}}.transmission-head{{display:flex;justify-content:space-between}}.transmission-head span{{font-size:11px;font-weight:800}}.transmission-head b{{padding:2px 7px;color:var(--green);font-size:9px;background:var(--green-soft);border-radius:99px}}.transmission>strong{{display:block;margin:6px 0 9px;font-size:12px}}.flow{{display:grid;grid-template-columns:62px 1fr;gap:3px 8px;align-items:start}}.flow span{{color:var(--muted);font-size:9px}}.flow p{{margin:0;font-size:10px}}.flow i{{grid-column:1/3;color:var(--line);font-style:normal}}
.dashboard{{padding:16px}}.dashboard img{{display:block;width:100%;height:auto;border:1px solid var(--line);border-radius:10px;background:#fff}}.dashboard figcaption{{margin-top:9px;color:var(--muted);font-size:10px}}.phase-map{{padding:16px;border-bottom:1px solid var(--line);background:#f8f6f0}}.phase-map-head{{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:12px}}.phase-map-head b{{font-size:13px}}.phase-map-head span{{max-width:680px;color:var(--muted);font-size:10px;text-align:right}}.phase-track{{display:grid;grid-template-columns:repeat(8,1fr);gap:6px}}.phase-step{{position:relative;min-height:118px;padding:10px 8px;border:1px solid var(--line);border-radius:9px;background:#fff}}.phase-step:before{{content:"";position:absolute;left:-7px;top:22px;width:7px;height:1px;background:var(--line)}}.phase-step:first-child:before{{display:none}}.phase-step>i{{display:grid;width:20px;height:20px;place-items:center;color:var(--muted);font-size:9px;font-style:normal;background:#efede7;border-radius:50%}}.phase-step>b{{display:block;margin:7px 0 2px;font-size:10px}}.phase-step>span{{display:block;min-height:30px;color:var(--muted);font-size:8px}}.phase-step>div{{display:flex;flex-wrap:wrap;gap:3px;margin-top:6px}}.phase-step em{{padding:3px 5px;font-size:7px;font-style:normal;border-radius:4px}}.phase-step.sector-active{{border:2px solid var(--green);background:var(--green-soft)}}.phase-step.theme-active{{box-shadow:inset 0 0 0 2px var(--navy)}}.sector-marker{{color:#fff;background:var(--green)}}.theme-marker{{color:#fff;background:var(--navy)}}.phase-legend{{margin:9px 0 0;color:var(--muted);font-size:9px}}.leadership-grid{{display:grid;grid-template-columns:1fr 1fr}}.leadership-column{{padding:16px}}.leadership-column+div{{border-left:1px solid var(--line)}}.leadership-column h3{{margin:0 0 12px;font-size:13px}}.lead-card{{margin-top:8px;padding:13px;border-radius:10px;box-shadow:none}}.lead-rank{{display:flex;gap:9px;align-items:center}}.lead-rank b{{display:grid;width:23px;height:23px;place-items:center;color:#fff;font-size:10px;background:var(--navy);border-radius:50%}}.lead-rank span{{font-size:11px;font-weight:750}}.score{{height:4px;margin:10px 0 8px;background:#e7e4dc;border-radius:99px;overflow:hidden}}.score i{{display:block;height:100%;background:var(--green)}}.lead-data{{display:flex;gap:12px;color:var(--muted);font-size:9px}}.lead-data strong{{color:var(--ink)}}.lead-card p{{margin:6px 0 0;color:var(--muted);font-size:10px}}.weak-note{{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:0 16px 16px}}.weak-note div{{padding:12px 14px;color:#654b24;font-size:10px;background:var(--amber-soft);border-radius:9px}}.weak-note b{{display:block;margin-bottom:2px}}
.checklist{{margin:0;padding:4px 20px 14px;list-style:none}}.checklist li{{display:grid;grid-template-columns:120px 1fr;gap:12px;padding:12px 0;border-bottom:1px solid var(--line);font-size:11px}}.checklist li:last-child{{border-bottom:0}}.checklist span{{color:var(--muted)}}.calendar-grid{{display:grid;grid-template-columns:1fr 1fr}}.calendar-panel{{overflow:auto}}.calendar-panel+div{{border-left:1px solid var(--line)}}.calendar-panel h3{{margin:0;padding:14px 16px;font-size:12px;border-bottom:1px solid var(--line)}}
.news-grid{{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;padding:16px}}.news-card{{padding:16px;border-radius:11px;box-shadow:none}}.news-meta{{display:flex;align-items:center;gap:7px}}.news-meta span{{padding:3px 6px;color:var(--green);font-size:9px;font-weight:800;background:var(--green-soft);border-radius:5px}}.news-meta b,.news-meta small,.news-card>small{{color:var(--muted);font-size:9px}}.news-read{{min-height:35px;margin:12px 0 9px;font-size:11px;font-weight:650}}.price-check{{padding:8px 9px;color:#315745;font-size:9px;background:var(--green-soft);border-radius:7px}}.news-card>a{{display:block;margin:10px 0 2px;color:var(--muted);font-size:9px;text-decoration:none}}
details{{border-top:1px solid var(--line)}}details summary{{padding:14px 18px;color:var(--muted);font-size:11px;font-weight:700;cursor:pointer;list-style:none}}details summary:after{{content:"＋";float:right}}details[open] summary:after{{content:"－"}}.table-wrap{{overflow:auto}}table{{width:100%;border-collapse:collapse;font-size:10px}}th,td{{padding:10px 12px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}}th{{color:var(--muted);background:#f0eee7}}td small{{display:block;color:var(--muted)}}td.rank{{color:var(--green);font-weight:800}}.empty{{padding:24px;color:var(--muted);font-size:11px;text-align:center}}footer{{padding:25px 0;color:var(--muted);font-size:10px}}
@media(max-width:850px){{.macro-grid,.leadership-grid,.calendar-grid{{grid-template-columns:1fr}}.quick-grid{{grid-template-columns:repeat(2,1fr)}}.phase-track{{grid-template-columns:repeat(4,1fr)}}.axis-list,.leadership-column+div,.calendar-panel+div{{border:0;border-top:1px solid var(--line)}}.changes{{grid-template-columns:1fr}}}}@media(max-width:620px){{.wrap{{width:min(100% - 22px,1180px)}}header{{padding-top:30px}}.quick-grid,.news-grid,.weak-note{{grid-template-columns:1fr}}.phase-map-head{{display:block}}.phase-map-head span{{display:block;margin-top:5px;text-align:left}}.phase-track{{grid-template-columns:repeat(2,1fr)}}.section-head{{display:block}}.section-head p{{margin-top:7px;text-align:left}}.checklist li{{grid-template-columns:1fr;gap:2px}}}}
</style>
</head>
<body>
<header><div class="wrap"><div class="eyebrow">US MARKET DAILY BRIEF</div><h1>{c['state']}</h1><p>{c['interpretation']}</p><div class="meta"><b>생성 기준 {c['as_of']}</b><b>미국 거래일 {c['market_date']}</b><b>위험 {c['risk_level']}</b><b>자동매매 없음</b></div></div></header>
<nav><div class="wrap"><a href="#summary">오늘의 결론</a><a href="#change">바뀐 것</a><a href="#macro">거시→가격</a><a href="#leadership">주도 섹터·테마</a><a href="#check">다음 확인</a><a href="#events">일정·뉴스</a><a href="#detail">상세자료</a></div></nav>
<main class="wrap">
<section class="brief" id="summary"><article class="verdict"><span class="kicker">TODAY'S CONCLUSION</span><h2>{c['conclusion']}</h2><p>섹터 순위와 테마 순위는 서로 다른 분류와 종목 묶음으로 독립 계산한다. 이는 자동 매수·매도 판단이 아니라 다음 거래일에 확인할 시장 가설이다.</p></article><div class="quick-grid"><article class="quick-card market"><span>전체 시장 흐름</span><strong>{c['state']}</strong><p>S&amp;P 최근 1개월 {c['sp500_return_20d']} · 시장 불안지수 {c['vix']} · 위험 {c['risk_level']}</p></article><article class="quick-card"><span>상승에 참여하는 종목</span><strong>{c['breadth_plain']}</strong><p>S&amp;P 500 종목 중 최근 50거래일 평균가격보다 높은 종목 · {c['breadth_above_ma50']}</p></article><article class="quick-card"><span>가장 강한 섹터 · 독립 순위</span><strong>{c['top_sector']}</strong><p>대장주 {c['top_sector_leader']} · {c['top_sector_phase']}</p></article><article class="quick-card"><span>가장 강한 테마 · 독립 순위</span><strong>{c['top_theme']}</strong><p>대장주 {c['top_theme_leader']} · {c['top_theme_phase']}</p></article></div></section>
<section class="section" id="change"><div class="section-head"><div><span class="kicker">WHAT CHANGED</span><h2>어제와 달라진 핵심</h2></div><p>단순 순위보다 현재 위치, 상대강도, 확산이 함께 유지되는지를 본다.</p></div><div class="changes"><article class="change-card"><span>시장 구조</span><b>S&amp;P 1일 {c['sp500_return_1d']}</b><p>20일 {c['sp500_return_20d']} · 상승 종목 {c['breadth_positive_1d']} · 위험 {c['risk_level']}</p></article><article class="change-card"><span>섹터 순위 급상승</span><b>{c['sector_mover']}</b><p>현재 {c['sector_mover_rank']}위 · 전일 {c['sector_mover_delta']} · 20일 상대 {c['sector_mover_relative_20d']} · {c['sector_mover_leader']}</p></article><article class="change-card"><span>테마 순위 급상승</span><b>{c['theme_mover']}</b><p>현재 {c['theme_mover_rank']}위 · 전일 {c['theme_mover_delta']} · 20일 상대 {c['theme_mover_relative_20d']} · {c['theme_mover_leader']}</p></article></div></section>
<section class="section" id="macro"><div class="section-head"><div><h2>거시 변화의 가격 반영</h2></div><p>왼쪽에서 거시 변수의 변화를 확인하고, 오른쪽에서 일반적 예상과 실제 가격 반응을 비교한다. 가격 반응 미약은 실제 수익률 변화가 ±0.1% 미만이라는 뜻이다.</p></div><div class="macro-grid"><div class="axis-list">{axis_rows}</div><div class="transmissions">{transmission_cards}</div></div></section>
<section class="section"><div class="section-head"><div><span class="kicker">MARKET STRUCTURE</span><h2>상승의 위치와 확산</h2></div><p>최근 3개월 지수 흐름, 시장 대비 섹터·테마 성과, 중기 상승에 참여하는 종목 비율을 함께 본다.</p></div><figure class="dashboard"><img src="market_dashboard.png" alt="미국 주요 지수, 섹터·테마 상대수익률과 상승 참여도 차트"><figcaption>‘중기 상승 참여도’는 각 종목이 최근 50거래일 평균가격보다 높은지 계산한 비율이다. 섹터 종합순위는 최근 1주·1개월·3개월 성과와 이 참여도를 함께 사용한다.</figcaption></figure></section>
<section class="section" id="leadership"><div class="section-head"><div><span class="kicker">LEADERSHIP</span><h2>어디가 강하고 누가 이끄는가</h2></div><p>섹터와 테마는 독립 순위다. 점수는 매수 확률이 아니라 시장 대비 성과와 상승 참여도의 합성값이다.</p></div><div class="phase-map"><div class="phase-map-head"><b>대장주 위치 지도 · 전체 8단계</b><span>왼쪽은 약세·회복 구간, 오른쪽은 상승·과열 구간이다. 종목은 단계 사이를 앞뒤로 이동하며 ‘상승 중 눌림’은 추세 안의 단기 조정이다.</span></div><div class="phase-track">{phase_guide}</div><p class="phase-legend">초록 표식: 섹터 1위 대장주 · 남색 표식: 테마 1위 대장주 · 단계는 매수 신호가 아니라 현재 가격 위치 설명</p></div><div class="leadership-grid"><div class="leadership-column"><h3>섹터 상위 5 · 산업 분류 기준</h3>{sector_cards}</div><div class="leadership-column"><h3>테마 상위 5 · 별도 종목 바스켓 기준</h3>{theme_cards}</div></div><div class="weak-note"><div><b>가장 약한 섹터</b>{c['weak_sector']} · 최근 1개월 시장 대비 {c['weak_sector_relative_20d']}</div><div><b>가장 약한 테마</b>{c['weak_theme']} · 최근 1개월 시장 대비 {c['weak_theme_relative_20d']}</div></div><details><summary>전체 섹터·테마 순위 보기</summary><div class="table-wrap"><table><thead><tr><th>순위</th><th>섹터·대장주</th><th>전일</th><th>1주</th><th>점수</th><th>1주 시장 대비</th><th>1개월 시장 대비</th><th>3개월 시장 대비</th><th>중기 상승 종목</th><th>단계</th></tr></thead><tbody>{sector_rows}</tbody></table><table><thead><tr><th>순위</th><th>테마·대장주</th><th>전일</th><th>1주</th><th>점수</th><th>1주 시장 대비</th><th>1개월 시장 대비</th><th>3개월 시장 대비</th><th>중기 상승 종목</th><th>단계</th></tr></thead><tbody>{theme_rows}</tbody></table></div></details></section>
<section class="section" id="check"><div class="section-head"><div><span class="kicker">NEXT SESSION</span><h2>다음 거래일에 확인할 것</h2></div><p>아래 조건이 약해지면 오늘의 해석도 다시 검토한다.</p></div><ul class="checklist">{checklist}</ul></section>
<section class="section" id="events"><div class="section-head"><div><span class="kicker">EVENTS &amp; NEWS</span><h2>일정과 시장을 움직인 사건</h2></div><p>공식 일정과 뉴스 사건을 구분하며, 뉴스는 관련 가격 반응까지 확인한다.</p></div><div class="calendar-grid"><div class="calendar-panel"><h3>해당 거래일 발표</h3><table><thead><tr><th>시각</th><th>발표</th><th>최근값</th><th>컨센서스</th><th>해석</th></tr></thead><tbody>{today_rows}</tbody></table></div><div class="calendar-panel"><h3>향후 주요 일정</h3><table><thead><tr><th>시각</th><th>발표</th><th>출처</th><th>해석</th></tr></thead><tbody>{upcoming_rows}</tbody></table></div></div><div class="news-grid">{news_cards}</div></section>
<section class="section" id="detail"><div class="section-head"><div><span class="kicker">REFERENCE</span><h2>상세 데이터</h2></div><p>핵심 판단 이후 필요한 경우에만 펼쳐 본다.</p></div><details><summary>지수·교차자산 전체 보기</summary><div class="table-wrap"><table><thead><tr><th>지수·자산</th><th>1일</th><th>5일</th><th>20일</th><th>200일선 괴리</th><th>차트 단계</th></tr></thead><tbody>{market_rows}</tbody></table></div></details><details><summary>섹터·테마 대장주와 위험 보기</summary><div class="table-wrap"><table><thead><tr><th>구분</th><th>그룹</th><th>회사명(티커)</th><th>20일</th><th>60일</th><th>차트 단계</th><th>확인할 위험</th></tr></thead><tbody>{leader_rows}</tbody></table></div></details><details><summary>거시 원자료 보기</summary><div class="table-wrap"><table><thead><tr><th>지표</th><th>최신값</th><th>직전 변화</th><th>관측일</th><th>의미</th></tr></thead><tbody>{macro_rows}</tbody></table></div></details></section>
<footer>가격 심볼 {c['successful_symbols']}/{c['requested_symbols']} · S&amp;P 500 스냅샷 {c['stock_snapshot_rows']}개 · 런타임 검증 {c['validation']}<br>이 문서는 시장 관찰 자료이며 매수·매도·보유 또는 목표 비중을 자동으로 결정하지 않는다. 뉴스 해석과 거시 전파 규칙은 1차 가설이므로 원문과 실제 가격 반응을 함께 확인해야 한다.</footer>
</main>
</body>
</html>"""
